### ISSUE TITLE
Byta namn på Shelly-produkter till mer användarvänligt

### ISSUE THREAD

**Issue by StefanJns** [StyraHem/tellstick-server-plugins#4]
Hej
När jag försöker sätta mer användarvänliga namn på mina Shelly-produkter, dvs byta från "shellyplug-s-2149B5" till tex "Fläkt sovrum" så fungerar det inte.
-Jag har provat att byta namn via  rename på min Tellstick Zwave 2. Jag har provat att gå in på min Zwave 2 och via Shelly-gränssittet byta namnet där men det fungerar inte.
-Jag har även provat att byta namnet i Telldus-appen men deet fungerar inte heller.
-Jag har även provat att byta namnet direkt i min internet router men det hjälper inte det heller.

**Comment by JoNy1970** [comment]
Gå in på lokala gränssnittet, där du installerade Shelly plugin, där har du meny Shelly och där står det "remane". funkade för mig.
![Telldus Shelly](https://user-images.githubusercontent.com/66470809/113594343-dcff0400-9637-11eb-891a-da14be1ef427.JPG)
![Telldus Shelly_1](https://user-images.githubusercontent.com/66470809/113594361-e2f4e500-9637-11eb-81e7-574883fbea66.JPG)

**Comment by StefanJns** [comment]
Tack för att du kollar och följer upp!
Jag vet inte vad jag hade för problem men till slut fungerade det. De första två gångerna gick det att byta namn men efter några minuter försvann det igen. Nu fungerar det!
Började fungera strax mitt inlägg här. 
stort tack!
/Stefan

**Comment by hakana** [comment]
Testade lite här också och det verkar fungera. Håller på att knopa ihop en ny release som kommer snart.

Stänger denna tråd nu.
